services:
- type: web
  name: todo-backend
  env: docker
  plan: starter
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: todo-db
      property: connectionString
- type: psql
  name: todo-db
  plan: starter
